# Generated by Django 6.0.1 on 2026-01-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botstate',
            name='max_trade_percent',
        ),
        migrations.AddField(
            model_name='botstate',
            name='buy_rsi',
            field=models.FloatField(default=45),
        ),
        migrations.AddField(
            model_name='botstate',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='botstate',
            name='sell_rsi',
            field=models.FloatField(default=55),
        ),
    ]
