# Generated by Django 6.0.1 on 2026-01-21 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_botstate_max_trade_percent_botstate_buy_rsi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'INFO'), ('ACTION', 'ACTION'), ('ERROR', 'ERROR')], max_length=10)),
                ('source', models.CharField(choices=[('BOT', 'BOT'), ('MANUAL', 'MANUAL'), ('SYSTEM', 'SYSTEM')], max_length=10)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
